name: "Run Codex"
description: "Codex のセットアップと実行を行う共通アクション"

inputs:
  codex_code_oauth_token:
    description: "Codex Code OAuth Token / API キー"
    required: false
    default: ""
  codex_auth_json:
    description: "Codex 認証情報（auth.json の Base64 エンコード値）"
    required: false
    default: ""
  github_token:
    description: "GitHub トークン（Codex GitHub Action が PR/Issue に書き込むために必要）"
    required: false
    default: ""
  prompt:
    description: "Codex に渡すプロンプト"
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate Codex credentials
      shell: bash
      env:
        CODEX_TOKEN: ${{ inputs.codex_code_oauth_token }}
        CODEX_AUTH_JSON: ${{ inputs.codex_auth_json }}
      run: |
        if [ -z "$CODEX_TOKEN" ] && [ -z "$CODEX_AUTH_JSON" ]; then
          echo "::error::codex_code_oauth_token または codex_auth_json のいずれかが必須です"
          exit 1
        fi

    - name: Run Codex GitHub Action (API キー)
      if: inputs.codex_code_oauth_token != ''
      uses: openai/codex-github-action@v1
      with:
        prompt: ${{ inputs.prompt }}
      env:
        OPENAI_API_KEY: ${{ inputs.codex_code_oauth_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Setup Node.js for Codex CLI
      if: inputs.codex_code_oauth_token == ''
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run Codex CLI (auth.json)
      if: inputs.codex_code_oauth_token == ''
      shell: bash
      env:
        PROMPT: ${{ inputs.prompt }}
        CODEX_AUTH_JSON: ${{ inputs.codex_auth_json }}
      run: |
        set -e
        # auth.json のセットアップ
        if [ -n "$CODEX_AUTH_JSON" ]; then
          CODEX_HOME="${HOME}/.codex"
          mkdir -p "$CODEX_HOME"
          if ! echo "$CODEX_AUTH_JSON" | base64 -d > "$CODEX_HOME/auth.json"; then
            echo "::error::codex_auth_json のデコードに失敗しました。有効な Base64 であることを確認してください。"
            exit 1
          fi
          chmod 600 "$CODEX_HOME/auth.json"
        fi
        # @openai/codex のインストールと実行
        npm install -g @openai/codex
        codex --full-auto "$PROMPT"
