name: "Run Claude Plan"
description: "コメント本文からモデル・ターン数を解決し、実装なしでプランを Issue コメントに投稿する"

inputs:
  github_token:
    description: "GitHub token"
    required: false
  comment_body:
    description: "トリガーとなったコメントの本文（モデル・ターン数の解決に使用）"
    required: true
  issue_number:
    description: "プランを投稿する Issue 番号"
    required: true
  claude_code_oauth_token:
    description: "Claude Code OAuth Token（mention_type が claude の場合に使用）"
    required: false
    default: ""
  codex_code_oauth_token:
    description: "Codex Code OAuth Token / API キー（mention_type が codex の場合に使用）"
    required: false
    default: ""
  codex_auth_json:
    description: "Codex 認証情報（auth.json の Base64 エンコード値）"
    required: false
    default: ""
  mention_type:
    description: "メンションの種類（claude または codex）"
    required: false
    default: "claude"
  default_model:
    description: "デフォルトの Claude モデル"
    required: false
    default: "sonnet"
  default_max_turns:
    description: "デフォルトの max turns（コードリーディングが少ない分、実装より多めに設定）"
    required: false
    default: "50"
  allowed_tools:
    description: "追加で許可するツール（改行区切り）"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Validate Claude token
      if: inputs.mention_type == 'claude'
      shell: bash
      env:
        CLAUDE_TOKEN: ${{ inputs.claude_code_oauth_token }}
      run: |
        if [ -z "$CLAUDE_TOKEN" ]; then
          echo "::error::claude_code_oauth_token は mention_type が claude の場合に必須です"
          exit 1
        fi

    - name: Resolve Claude options
      if: inputs.mention_type == 'claude'
      id: opts
      uses: actions/github-script@v7
      env:
        COMMENT_BODY: ${{ inputs.comment_body }}
      with:
        script: |
          const body = process.env.COMMENT_BODY || "";

          const model =
            body.includes("[sonnet]") ? "sonnet" :
            body.includes("[opus]")   ? "opus"   :
            body.includes("[haiku]")  ? "haiku"  : "${{ inputs.default_model }}";

          const m = body.match(/\[(?:turns|max-turns)=(\d+)\]/);
          const maxTurns = m ? Number(m[1]) : Number("${{ inputs.default_max_turns }}");

          core.setOutput("model", model);
          core.setOutput("max_turns", String(maxTurns));

    - name: Build allowed tools
      if: inputs.mention_type == 'claude'
      id: tools
      shell: bash
      env:
        CUSTOM_TOOLS: ${{ inputs.allowed_tools }}
      run: |
        TOOLS=""
        if [ -n "$CUSTOM_TOOLS" ]; then
          while IFS= read -r tool; do
            [ -n "$tool" ] && TOOLS="$TOOLS --allowedTools \"$tool\""
          done <<< "$CUSTOM_TOOLS"
        fi
        echo "tools=$TOOLS" >> $GITHUB_OUTPUT

    - name: Load prompt
      id: prompt
      shell: bash
      env:
        ISSUE_NUMBER: ${{ inputs.issue_number }}
      run: |
        PROMPT_FILE="docs/agent/PLAN_PROMPT.md"

        if [ ! -f "$PROMPT_FILE" ]; then
          echo "::error::Prompt file not found: $PROMPT_FILE"
          exit 1
        fi

        # プロンプトファイルを読み込み、プレースホルダーを置換
        PROMPT=$(cat "$PROMPT_FILE" | sed "s/{{ISSUE_NUMBER}}/$ISSUE_NUMBER/g")

        # 複数行の出力を GITHUB_OUTPUT に設定
        echo "content<<EOF" >> $GITHUB_OUTPUT
        echo "$PROMPT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Run Claude Plan Action (Custom token mode)
      if: inputs.mention_type == 'claude' && inputs.github_token != ''
      uses: anthropics/claude-code-action@v1
      with:
        github_token: ${{ inputs.github_token }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: ${{ steps.prompt.outputs.content }}
        claude_args: >-
          --model ${{ steps.opts.outputs.model }}
          --max-turns ${{ steps.opts.outputs.max_turns }}
          --allowedTools "Bash(gh issue comment:*),Bash(gh issue view:*),Read,Glob,Grep"
          ${{ steps.tools.outputs.tools }}

    - name: Run Claude Plan Action (App mode)
      if: inputs.mention_type == 'claude' && inputs.github_token == ''
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: ${{ steps.prompt.outputs.content }}
        claude_args: >-
          --model ${{ steps.opts.outputs.model }}
          --max-turns ${{ steps.opts.outputs.max_turns }}
          --allowedTools "Bash(gh issue comment:*),Bash(gh issue view:*),Read,Glob,Grep"
          ${{ steps.tools.outputs.tools }}

    - name: Run Codex
      if: inputs.mention_type == 'codex'
      uses: ./.github/actions/run-codex
      with:
        codex_code_oauth_token: ${{ inputs.codex_code_oauth_token }}
        codex_auth_json: ${{ inputs.codex_auth_json }}
        github_token: ${{ inputs.github_token }}
        prompt: ${{ steps.prompt.outputs.content }}
        comment_body: ${{ inputs.comment_body }}
        issue_number: ${{ inputs.issue_number }}
        # plan は Issue コンテキストのみ（PR なし）
        auto_commit: "false"
