name: "Run Claude Review"
description: "Runs the Claude Code Action for PR reviews"

inputs:
  claude_code_oauth_token:
    description: "Claude Code OAuth Token（mention_type が claude の場合に使用）"
    required: false
    default: ""
  codex_code_oauth_token:
    description: "Codex Code OAuth Token / API キー（mention_type が codex の場合に使用）"
    required: false
    default: ""
  codex_auth_json:
    description: "Codex 認証情報（auth.json の Base64 エンコード値）"
    required: false
    default: ""
  mention_type:
    description: "メンションの種類（claude または codex）"
    required: false
    default: "claude"
  model:
    description: "Claude model (sonnet/opus/haiku)"
    required: false
    default: "haiku"
  max_turns:
    description: "Max turns"
    required: false
    default: "30"
  prompt:
    description: "Review prompt"
    required: false
    default: "/review"
  allowed_bots:
    description: "Allowed bots"
    required: false
    default: "claude[bot]"

runs:
  using: "composite"
  steps:
    - name: Validate token
      shell: bash
      env:
        MENTION_TYPE: ${{ inputs.mention_type }}
        CLAUDE_TOKEN: ${{ inputs.claude_code_oauth_token }}
        CODEX_TOKEN: ${{ inputs.codex_code_oauth_token }}
        CODEX_AUTH_JSON: ${{ inputs.codex_auth_json }}
      run: |
        if [ "$MENTION_TYPE" = "codex" ] && [ -z "$CODEX_TOKEN" ] && [ -z "$CODEX_AUTH_JSON" ]; then
          echo "::error::codex_code_oauth_token または codex_auth_json は mention_type が codex の場合に必須です"
          exit 1
        fi
        if [ "$MENTION_TYPE" != "codex" ] && [ -z "$CLAUDE_TOKEN" ]; then
          echo "::error::claude_code_oauth_token は mention_type が claude の場合に必須です"
          exit 1
        fi

    - name: Run Claude Review Action
      if: inputs.mention_type != 'codex'
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: "${{ inputs.prompt }}"
        track_progress: true
        allowed_bots: "${{ inputs.allowed_bots }}"
        claude_args: |
          --model ${{ inputs.model }}
          --max-turns ${{ inputs.max_turns }}
          --allowedTools "Bash(gh pr list:*),Bash(gh pr view:*),Bash(gh pr diff:*),Bash(gh pr comment:*)"

    - name: Setup Codex authentication
      if: inputs.mention_type == 'codex' && inputs.codex_auth_json != ''
      shell: bash
      env:
        CODEX_AUTH_JSON: ${{ inputs.codex_auth_json }}
      run: |
        CODEX_HOME="${HOME}/.codex"
        mkdir -p "$CODEX_HOME"
        echo "$CODEX_AUTH_JSON" | base64 -d > "$CODEX_HOME/auth.json"
        chmod 600 "$CODEX_HOME/auth.json"

    - name: Run Codex GitHub Action (review)
      if: inputs.mention_type == 'codex'
      uses: openai/codex-github-action@v1
      with:
        prompt: ${{ inputs.prompt }}
      env:
        OPENAI_API_KEY: ${{ inputs.codex_code_oauth_token }}
