name: "Run Claude Review"
description: "Runs the Claude Code Action for PR reviews"

inputs:
  claude_code_oauth_token:
    description: "Claude Code OAuth Token"
    required: true
  comment_body:
    description: "トリガーとなったコメントの本文（モデル・ターン数の解決に使用）。コメントによる発火時のみ有効"
    required: false
    default: ""
  model:
    description: "Claude model (sonnet/opus/haiku)"
    required: false
    default: "opus"
  max_turns:
    description: "Max turns"
    required: false
    default: "30"
  prompt:
    description: "Review prompt"
    required: false
    default: "/review"
  allowed_bots:
    description: "Allowed bots"
    required: false
    default: "claude[bot]"

runs:
  using: "composite"
  steps:
    - name: Resolve Claude options
      id: opts
      uses: actions/github-script@v7
      env:
        COMMENT_BODY: ${{ inputs.comment_body }}
      with:
        script: |
          const body = process.env.COMMENT_BODY || "";

          const model =
            body.includes("[sonnet]") ? "sonnet" :
            body.includes("[opus]")   ? "opus"   :
            body.includes("[haiku]")  ? "haiku"  : "${{ inputs.model }}";

          const m = body.match(/\[(?:turns|max-turns)=(\d+)\]/);
          const maxTurns = m ? Number(m[1]) : Number("${{ inputs.max_turns }}");

          core.setOutput("model", model);
          core.setOutput("max_turns", String(maxTurns));

    - name: Run Claude Review Action
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: "${{ inputs.prompt }}"
        track_progress: true
        allowed_bots: "${{ inputs.allowed_bots }}"
        claude_args: |
          --model ${{ steps.opts.outputs.model }}
          --max-turns ${{ steps.opts.outputs.max_turns }}
          --allowedTools "Bash(gh pr list:*),Bash(gh pr view:*),Bash(gh pr diff:*),Bash(gh pr comment:*)"
