name: "Run Claude Review"
description: "Runs the Claude Code Action for PR reviews"

inputs:
  github_token:
    description: "GitHub token"
    required: false
  claude_code_oauth_token:
    description: "Claude Code OAuth Token（mention_type が claude の場合に使用）"
    required: false
    default: ""
  codex_code_oauth_token:
    description: "Codex Code OAuth Token / API キー（mention_type が codex の場合に使用）"
    required: false
    default: ""
  codex_auth_json:
    description: "Codex 認証情報（auth.json の Base64 エンコード値）"
    required: false
    default: ""
  mention_type:
    description: "メンションの種類（claude または codex）"
    required: false
    default: "claude"
  issue_number:
    description: "Issue/PR 番号（Codex のコメント投稿に使用）"
    required: false
    default: ""
  model:
    description: "Claude model (sonnet/opus/haiku)"
    required: false
    default: "haiku"
  max_turns:
    description: "Max turns"
    required: false
    default: "30"
  prompt:
    description: "Review prompt"
    required: false
    default: "/review"
  allowed_bots:
    description: "Allowed bots"
    required: false
    default: "claude[bot]"

runs:
  using: "composite"
  steps:
    - name: Validate Claude token
      if: inputs.mention_type != 'codex'
      shell: bash
      env:
        CLAUDE_TOKEN: ${{ inputs.claude_code_oauth_token }}
      run: |
        if [ -z "$CLAUDE_TOKEN" ]; then
          echo "::error::claude_code_oauth_token は mention_type が claude の場合に必須です"
          exit 1
        fi

    - name: Run Claude Review Action
      if: inputs.mention_type != 'codex'
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: "${{ inputs.prompt }}"
        track_progress: true
        allowed_bots: "${{ inputs.allowed_bots }}"
        claude_args: |
          --model ${{ inputs.model }}
          --max-turns ${{ inputs.max_turns }}
          --allowedTools "Bash(gh pr list:*),Bash(gh pr view:*),Bash(gh pr diff:*),Bash(gh pr comment:*)"

    - name: Build Codex review prompt
      if: inputs.mention_type == 'codex'
      id: codex_prompt
      shell: bash
      env:
        PROMPT: ${{ inputs.prompt }}
      run: |
        # /review は Claude 固有のコマンドのため、Codex 用のレビュープロンプトに変換
        if [ "$PROMPT" = "/review" ]; then
          CODEX_PROMPT="この PR の変更内容をレビューしてください。バグ、セキュリティ問題、パフォーマンスの問題、コードの品質について確認し、改善提案を含むレビューコメントを投稿してください。"
        else
          CODEX_PROMPT="$PROMPT"
        fi
        echo "content<<EOF" >> $GITHUB_OUTPUT
        echo "$CODEX_PROMPT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Run Codex
      if: inputs.mention_type == 'codex'
      uses: ./.github/actions/run-codex
      with:
        codex_code_oauth_token: ${{ inputs.codex_code_oauth_token }}
        codex_auth_json: ${{ inputs.codex_auth_json }}
        github_token: ${{ inputs.github_token }}
        prompt: ${{ steps.codex_prompt.outputs.content }}
        issue_number: ${{ inputs.issue_number }}
        auto_commit: "false"
