name: "Run Codex Breakdown"
description: "Breaks down the plan into tasks and adds issues to the milestone"

inputs:
  comment_body:
    description: "Trigger comment body"
    required: true
  issue_number:
    description: "Parent issue number"
    required: true
  milestone_number:
    description: "Milestone number"
    required: true
  milestone_title:
    description: "Milestone title"
    required: true
  openai_api_key:
    description: "OpenAI or Azure OpenAI API key"
    required: true
  responses_api_endpoint:
    description: "Optional Responses API endpoint (for Azure, etc.)"
    required: false
    default: ""
  default_model:
    description: "Default model"
    required: false
    default: "gpt-5-codex"
  default_effort:
    description: "Default effort"
    required: false
    default: "high"
  default_max_turns:
    description: "Default max turns"
    required: false
    default: "100"
  codex_args:
    description: "Additional codex exec args"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Resolve Codex options
      id: opts
      uses: actions/github-script@v7
      env:
        COMMENT_BODY: ${{ inputs.comment_body }}
      with:
        script: |
          const body = process.env.COMMENT_BODY || "";
          const modelMatch = body.match(/\[model=([^\]]+)\]/i);
          const effortMatch = body.match(/\[effort=(low|medium|high)\]/i);
          const turnsMatch = body.match(/\[(?:turns|max-turns)=(\d+)\]/i);

          const model = modelMatch ? modelMatch[1].trim() : "${{ inputs.default_model }}";
          const effort = effortMatch ? effortMatch[1].toLowerCase().trim() : "${{ inputs.default_effort }}";
          const maxTurns = turnsMatch ? Number(turnsMatch[1]) : Number("${{ inputs.default_max_turns }}");

          core.setOutput("model", model);
          core.setOutput("effort", effort);
          core.setOutput("max_turns", String(maxTurns));

    - name: Load prompt
      id: prompt
      shell: bash
      env:
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        MILESTONE_TITLE: ${{ inputs.milestone_title }}
      run: |
        PROMPT_FILE="docs/agent/BREAKDOWN_PROMPT.md"
        if [ ! -f "$PROMPT_FILE" ]; then
          echo "::error::Prompt file not found: $PROMPT_FILE"
          exit 1
        fi

        PROMPT=$(cat "$PROMPT_FILE" | \
          sed "s/{{ISSUE_NUMBER}}/$ISSUE_NUMBER/g" | \
          sed "s/{{MILESTONE_TITLE}}/$MILESTONE_TITLE/g")

        echo "content<<EOF" >> "$GITHUB_OUTPUT"
        echo "$PROMPT" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - name: Run Codex Breakdown
      id: codex
      uses: openai/codex-action@v1
      with:
        openai-api-key: ${{ inputs.openai_api_key }}
        responses-api-endpoint: ${{ inputs.responses_api_endpoint }}
        sandbox: danger-full-access
        safety-strategy: drop-sudo
        prompt: ${{ steps.prompt.outputs.content }}
        model: ${{ steps.opts.outputs.model }}
        effort: ${{ steps.opts.outputs.effort }}
        codex-args: >-
          --max-turns ${{ steps.opts.outputs.max_turns }}
          ${{ inputs.codex_args }}

    - name: Post breakdown summary
      if: steps.codex.outputs.final-message != ''
      uses: actions/github-script@v7
      env:
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        CODEX_FINAL_MESSAGE: ${{ steps.codex.outputs.final-message }}
      with:
        script: |
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: Number(process.env.ISSUE_NUMBER),
            body: process.env.CODEX_FINAL_MESSAGE,
          });
