name: "Run Claude Breakdown"
description: "最新のプランコメントを元に並行作業可能な粒度で Issue を分解作成し、Milestone に追加する"

inputs:
  github_token:
    description: "GitHub token"
    required: false
  comment_body:
    description: "トリガーとなったコメントの本文（モデル・ターン数の解決に使用）"
    required: true
  issue_number:
    description: "プランコメントを参照する Issue 番号"
    required: true
  milestone_number:
    description: "分解したタスクを追加する Milestone 番号"
    required: true
  milestone_title:
    description: "Milestone タイトル"
    required: true
  claude_code_oauth_token:
    description: "Claude Code OAuth Token（mention_type が claude の場合に使用）"
    required: false
    default: ""
  codex_code_oauth_token:
    description: "Codex Code OAuth Token / API キー（mention_type が codex の場合に使用）"
    required: false
    default: ""
  codex_auth_json:
    description: "Codex 認証情報（auth.json の Base64 エンコード値）"
    required: false
    default: ""
  mention_type:
    description: "メンションの種類（claude または codex）"
    required: false
    default: "claude"
  default_model:
    description: "デフォルトの Claude モデル（Issue の丁寧さ・的確さが実装品質に直結するため opus 推奨）"
    required: false
    default: "opus"
  default_max_turns:
    description: "デフォルトの max turns"
    required: false
    default: "100"
  allowed_tools:
    description: "追加で許可するツール（改行区切り）"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Validate Claude token
      if: inputs.mention_type == 'claude'
      shell: bash
      env:
        CLAUDE_TOKEN: ${{ inputs.claude_code_oauth_token }}
      run: |
        if [ -z "$CLAUDE_TOKEN" ]; then
          echo "::error::claude_code_oauth_token は mention_type が claude の場合に必須です"
          exit 1
        fi

    - name: Resolve Claude options
      if: inputs.mention_type == 'claude'
      id: opts
      uses: actions/github-script@v7
      env:
        COMMENT_BODY: ${{ inputs.comment_body }}
      with:
        script: |
          const body = process.env.COMMENT_BODY || "";

          const model =
            body.includes("[sonnet]") ? "sonnet" :
            body.includes("[opus]")   ? "opus"   :
            body.includes("[haiku]")  ? "haiku"  : "${{ inputs.default_model }}";

          const m = body.match(/\[(?:turns|max-turns)=(\d+)\]/);
          const maxTurns = m ? Number(m[1]) : Number("${{ inputs.default_max_turns }}");

          core.setOutput("model", model);
          core.setOutput("max_turns", String(maxTurns));

    - name: Build allowed tools
      if: inputs.mention_type == 'claude'
      id: tools
      shell: bash
      env:
        CUSTOM_TOOLS: ${{ inputs.allowed_tools }}
      run: |
        TOOLS=""
        if [ -n "$CUSTOM_TOOLS" ]; then
          while IFS= read -r tool; do
            [ -n "$tool" ] && TOOLS="$TOOLS --allowedTools \"$tool\""
          done <<< "$CUSTOM_TOOLS"
        fi
        echo "tools=$TOOLS" >> $GITHUB_OUTPUT

    - name: Load prompt
      id: prompt
      shell: bash
      env:
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        MILESTONE_TITLE: ${{ inputs.milestone_title }}
      run: |
        PROMPT_FILE="docs/agent/BREAKDOWN_PROMPT.md"

        if [ ! -f "$PROMPT_FILE" ]; then
          echo "::error::Prompt file not found: $PROMPT_FILE"
          exit 1
        fi

        # プロンプトファイルを読み込み、プレースホルダーを置換
        PROMPT=$(cat "$PROMPT_FILE" | \
          sed "s/{{ISSUE_NUMBER}}/$ISSUE_NUMBER/g" | \
          sed "s/{{MILESTONE_TITLE}}/$MILESTONE_TITLE/g")

        # 複数行の出力を GITHUB_OUTPUT に設定
        echo "content<<EOF" >> $GITHUB_OUTPUT
        echo "$PROMPT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Run Claude Breakdown Action (Custom token mode)
      if: inputs.mention_type == 'claude' && inputs.github_token != ''
      uses: anthropics/claude-code-action@v1
      with:
        github_token: ${{ inputs.github_token }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: ${{ steps.prompt.outputs.content }}
        claude_args: >-
          --model ${{ steps.opts.outputs.model }}
          --max-turns ${{ steps.opts.outputs.max_turns }}
          --allowedTools "Bash(gh issue create:*),Bash(gh issue view:*),Bash(gh issue list:*),Bash(gh issue comment:*),Read,Glob,Grep"
          ${{ steps.tools.outputs.tools }}

    - name: Run Claude Breakdown Action (App mode)
      if: inputs.mention_type == 'claude' && inputs.github_token == ''
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: ${{ steps.prompt.outputs.content }}
        claude_args: >-
          --model ${{ steps.opts.outputs.model }}
          --max-turns ${{ steps.opts.outputs.max_turns }}
          --allowedTools "Bash(gh issue create:*),Bash(gh issue view:*),Bash(gh issue list:*),Bash(gh issue comment:*),Read,Glob,Grep"
          ${{ steps.tools.outputs.tools }}

    - name: Build Codex breakdown prompt
      if: inputs.mention_type == 'codex'
      id: codex_prompt
      shell: bash
      env:
        ORIGINAL_PROMPT: ${{ steps.prompt.outputs.content }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        MILESTONE_TITLE: ${{ inputs.milestone_title }}
      run: |
        # Codex 用のプロンプトに Issue 作成の補助指示を追加
        # Codex の --full-auto サンドボックスではネットワークがブロックされるため、
        # gh CLI は使用できない。JSON ファイル出力でワークフロー側が Issue を作成する
        CODEX_PROMPT="${ORIGINAL_PROMPT}

        ---
        【重要: Issue 作成について】
        Codex のサンドボックス環境では \`gh\` コマンドは使用できません。
        代わりに、以下の JSON 形式で \`.codex-issues.json\` ファイルに書き出してください。
        ワークフローが自動的にこの JSON を読み取り、Issue を作成します。

        \`\`\`json
        [
          {
            \"title\": \"Issue タイトル\",
            \"body\": \"Issue 本文（Markdown）\",
            \"milestone\": \"${MILESTONE_TITLE}\"
          }
        ]
        \`\`\`"

        echo "content<<CODEX_BREAKDOWN_EOF" >> $GITHUB_OUTPUT
        echo "$CODEX_PROMPT" >> $GITHUB_OUTPUT
        echo "CODEX_BREAKDOWN_EOF" >> $GITHUB_OUTPUT

    - name: Run Codex
      if: inputs.mention_type == 'codex'
      id: codex_run
      uses: ./.github/actions/run-codex
      with:
        codex_code_oauth_token: ${{ inputs.codex_code_oauth_token }}
        codex_auth_json: ${{ inputs.codex_auth_json }}
        github_token: ${{ inputs.github_token }}
        prompt: ${{ steps.codex_prompt.outputs.content }}
        comment_body: ${{ inputs.comment_body }}
        issue_number: ${{ inputs.issue_number }}
        # breakdown は Issue コンテキストのみ（PR なし）
        auto_commit: "false"

    # Codex が .codex-issues.json を生成した場合、ワークフローで Issue を作成
    - name: Create issues from Codex output
      if: inputs.mention_type == 'codex'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        MILESTONE_TITLE: ${{ inputs.milestone_title }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
      run: |
        if [ ! -f .codex-issues.json ]; then
          echo "::warning::.codex-issues.json が見つかりません。Codex が Issue 定義の生成に失敗した可能性があります。"
          exit 0
        fi

        echo "Codex が生成した Issue 定義を読み込み、Issue を作成します..."
        CREATED_ISSUES=""

        # JSON 配列の各要素を処理
        ISSUE_COUNT=$(jq length .codex-issues.json)
        for i in $(seq 0 $((ISSUE_COUNT - 1))); do
          TITLE=$(jq -r ".[$i].title" .codex-issues.json)
          BODY=$(jq -r ".[$i].body" .codex-issues.json)
          MILESTONE=$(jq -r ".[$i].milestone // \"${MILESTONE_TITLE}\"" .codex-issues.json)

          echo "Issue 作成中: ${TITLE}"
          if NEW_ISSUE_URL=$(gh issue create --title "$TITLE" --body "$BODY" --milestone "$MILESTONE" 2>&1); then
            echo "  作成成功: ${NEW_ISSUE_URL}"
            CREATED_ISSUES="${CREATED_ISSUES}\n- ${NEW_ISSUE_URL} ${TITLE}"
          else
            echo "::warning::Issue 作成に失敗しました: ${TITLE} - ${NEW_ISSUE_URL}"
          fi
        done

        # 作成結果を元 Issue にコメント
        if [ -n "$CREATED_ISSUES" ]; then
          COMMENT_BODY="## タスク分解が完了しました（Codex）

        以下の Issue を作成し、Milestone 「${MILESTONE_TITLE}」に追加しました:
        $(echo -e "$CREATED_ISSUES")"

          gh issue comment "$ISSUE_NUMBER" --body "$COMMENT_BODY" || echo "::warning::サマリーコメントの投稿に失敗しました"
        fi

        # クリーンアップ
        rm -f .codex-issues.json
