name: "Run Claude Breakdown"
description: "最新のプランコメントを元に並行作業可能な粒度で Issue を分解作成し、Milestone に追加する"

inputs:
  github_token:
    description: "GitHub token"
    required: false
  comment_body:
    description: "トリガーとなったコメントの本文（モデル・ターン数の解決に使用）"
    required: true
  issue_number:
    description: "プランコメントを参照する Issue 番号"
    required: true
  milestone_number:
    description: "分解したタスクを追加する Milestone 番号"
    required: true
  milestone_title:
    description: "Milestone タイトル"
    required: true
  claude_code_oauth_token:
    description: "Claude Code OAuth Token（mention_type が claude の場合に使用）"
    required: false
    default: ""
  codex_code_oauth_token:
    description: "Codex Code OAuth Token（mention_type が codex の場合に使用）"
    required: false
    default: ""
  mention_type:
    description: "メンションの種類（claude または codex）"
    required: false
    default: "claude"
  default_model:
    description: "デフォルトの Claude モデル（Issue の丁寧さ・的確さが実装品質に直結するため opus 推奨）"
    required: false
    default: "opus"
  default_max_turns:
    description: "デフォルトの max turns"
    required: false
    default: "100"
  allowed_tools:
    description: "追加で許可するツール（改行区切り）"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Validate token
      shell: bash
      env:
        MENTION_TYPE: ${{ inputs.mention_type }}
        CLAUDE_TOKEN: ${{ inputs.claude_code_oauth_token }}
        CODEX_TOKEN: ${{ inputs.codex_code_oauth_token }}
      run: |
        if [ "$MENTION_TYPE" = "codex" ] && [ -z "$CODEX_TOKEN" ]; then
          echo "::error::codex_code_oauth_token は mention_type が codex の場合に必須です"
          exit 1
        fi
        if [ "$MENTION_TYPE" != "codex" ] && [ -z "$CLAUDE_TOKEN" ]; then
          echo "::error::claude_code_oauth_token は mention_type が claude の場合に必須です"
          exit 1
        fi

    - name: Resolve Claude options
      id: opts
      uses: actions/github-script@v7
      env:
        COMMENT_BODY: ${{ inputs.comment_body }}
      with:
        script: |
          const body = process.env.COMMENT_BODY || "";

          const model =
            body.includes("[sonnet]") ? "sonnet" :
            body.includes("[opus]")   ? "opus"   :
            body.includes("[haiku]")  ? "haiku"  : "${{ inputs.default_model }}";

          const m = body.match(/\[(?:turns|max-turns)=(\d+)\]/);
          const maxTurns = m ? Number(m[1]) : Number("${{ inputs.default_max_turns }}");

          core.setOutput("model", model);
          core.setOutput("max_turns", String(maxTurns));

    - name: Build allowed tools
      id: tools
      shell: bash
      env:
        CUSTOM_TOOLS: ${{ inputs.allowed_tools }}
      run: |
        TOOLS=""
        if [ -n "$CUSTOM_TOOLS" ]; then
          while IFS= read -r tool; do
            [ -n "$tool" ] && TOOLS="$TOOLS --allowedTools \"$tool\""
          done <<< "$CUSTOM_TOOLS"
        fi
        echo "tools=$TOOLS" >> $GITHUB_OUTPUT

    - name: Load prompt
      id: prompt
      shell: bash
      env:
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        MILESTONE_TITLE: ${{ inputs.milestone_title }}
      run: |
        PROMPT_FILE="docs/agent/BREAKDOWN_PROMPT.md"

        if [ ! -f "$PROMPT_FILE" ]; then
          echo "::error::Prompt file not found: $PROMPT_FILE"
          exit 1
        fi

        # プロンプトファイルを読み込み、プレースホルダーを置換
        PROMPT=$(cat "$PROMPT_FILE" | \
          sed "s/{{ISSUE_NUMBER}}/$ISSUE_NUMBER/g" | \
          sed "s/{{MILESTONE_TITLE}}/$MILESTONE_TITLE/g")

        # 複数行の出力を GITHUB_OUTPUT に設定
        echo "content<<EOF" >> $GITHUB_OUTPUT
        echo "$PROMPT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Run Claude Breakdown Action (Custom token mode)
      if: inputs.mention_type != 'codex' && inputs.github_token != '' && inputs.github_token != null
      uses: anthropics/claude-code-action@v1
      with:
        github_token: ${{ inputs.github_token }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: ${{ steps.prompt.outputs.content }}
        claude_args: >-
          --model ${{ steps.opts.outputs.model }}
          --max-turns ${{ steps.opts.outputs.max_turns }}
          --allowedTools "Bash(gh issue create:*),Bash(gh issue view:*),Bash(gh issue list:*),Bash(gh issue comment:*),Read,Glob,Grep"
          ${{ steps.tools.outputs.tools }}

    - name: Run Claude Breakdown Action (App mode)
      if: inputs.mention_type != 'codex' && (inputs.github_token == '' || inputs.github_token == null)
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: ${{ steps.prompt.outputs.content }}
        claude_args: >-
          --model ${{ steps.opts.outputs.model }}
          --max-turns ${{ steps.opts.outputs.max_turns }}
          --allowedTools "Bash(gh issue create:*),Bash(gh issue view:*),Bash(gh issue list:*),Bash(gh issue comment:*),Read,Glob,Grep"
          ${{ steps.tools.outputs.tools }}

    - name: Install Codex CLI
      if: inputs.mention_type == 'codex'
      shell: bash
      run: npm install -g @openai/codex

    - name: Run Codex (breakdown)
      if: inputs.mention_type == 'codex'
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.codex_code_oauth_token }}
        PROMPT: ${{ steps.prompt.outputs.content }}
      run: |
        codex --approval-mode full-auto --quiet "$PROMPT"
