name: "Run Claude"
description: "Resolves options, builds tools, and runs the Claude Code Action"

inputs:
  github_token:
    description: "GitHub token"
    required: false
  comment_body:
    description: "The body of the comment that triggered the workflow"
    required: true
  claude_code_oauth_token:
    description: "Claude Code OAuth Token（mention_type が claude の場合に使用）"
    required: false
    default: ""
  codex_code_oauth_token:
    description: "Codex Code OAuth Token / API キー（mention_type が codex の場合に使用）"
    required: false
    default: ""
  codex_auth_json:
    description: "Codex 認証情報（auth.json の Base64 エンコード値）"
    required: false
    default: ""
  mention_type:
    description: "メンションの種類（claude または codex）"
    required: false
    default: "claude"
  default_model:
    description: "Default Claude model"
    required: false
    default: "sonnet"
  default_max_turns:
    description: "Default max turns"
    required: false
    default: "100"
  allowed_tools:
    description: "Additional allowed tools (newline-separated)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Check trigger condition
      id: trigger
      shell: bash
      env:
        COMMENT_BODY: ${{ inputs.comment_body }}
      run: |
        if [[ "$COMMENT_BODY" =~ @(claude|codex) ]]; then
          echo "triggered=true" >> $GITHUB_OUTPUT
        else
          echo "Comment does not contain '@claude' or '@codex'. Skipping."
          echo "triggered=false" >> $GITHUB_OUTPUT
        fi

    - name: Validate Claude token
      if: steps.trigger.outputs.triggered == 'true' && inputs.mention_type != 'codex'
      shell: bash
      env:
        CLAUDE_TOKEN: ${{ inputs.claude_code_oauth_token }}
      run: |
        if [ -z "$CLAUDE_TOKEN" ]; then
          echo "::error::claude_code_oauth_token は mention_type が claude の場合に必須です"
          exit 1
        fi

    - name: Resolve Claude options
      if: steps.trigger.outputs.triggered == 'true' && inputs.mention_type != 'codex'
      id: opts
      uses: actions/github-script@v7
      env:
        COMMENT_BODY: ${{ inputs.comment_body }}
      with:
        script: |
          const body = process.env.COMMENT_BODY || "";

          const model =
            body.includes("[sonnet]") ? "sonnet" :
            body.includes("[opus]")   ? "opus"   :
            body.includes("[haiku]")  ? "haiku"  : "${{ inputs.default_model }}";

          const m = body.match(/\[(?:turns|max-turns)=(\d+)\]/);
          const maxTurns = m ? Number(m[1]) : Number("${{ inputs.default_max_turns }}");

          core.setOutput("model", model);
          core.setOutput("max_turns", String(maxTurns));

    - name: Build allowed tools
      if: steps.trigger.outputs.triggered == 'true' && inputs.mention_type != 'codex'
      id: tools
      shell: bash
      env:
        CUSTOM_TOOLS: ${{ inputs.allowed_tools }}
      run: |
        TOOLS=""
        if [ -n "$CUSTOM_TOOLS" ]; then
          while IFS= read -r tool; do
            [ -n "$tool" ] && TOOLS="$TOOLS --allowedTools \"$tool\""
          done <<< "$CUSTOM_TOOLS"
        fi
        echo "tools=$TOOLS" >> $GITHUB_OUTPUT

    - name: Run Claude Code Action (Custom token mode)
      if: steps.trigger.outputs.triggered == 'true' && inputs.mention_type != 'codex' && inputs.github_token != ''
      uses: anthropics/claude-code-action@v1
      with:
        github_token: ${{ inputs.github_token }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        claude_args: >-
          --model ${{ steps.opts.outputs.model }}
          --max-turns ${{ steps.opts.outputs.max_turns }}
          ${{ steps.tools.outputs.tools }}

    - name: Run Claude Code Action (App mode)
      if: steps.trigger.outputs.triggered == 'true' && inputs.mention_type != 'codex' && inputs.github_token == ''
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        claude_args: >-
          --model ${{ steps.opts.outputs.model }}
          --max-turns ${{ steps.opts.outputs.max_turns }}
          ${{ steps.tools.outputs.tools }}

    - name: Run Codex
      if: steps.trigger.outputs.triggered == 'true' && inputs.mention_type == 'codex'
      uses: ./.github/actions/run-codex
      with:
        codex_code_oauth_token: ${{ inputs.codex_code_oauth_token }}
        codex_auth_json: ${{ inputs.codex_auth_json }}
        github_token: ${{ inputs.github_token }}
        prompt: ${{ inputs.comment_body }}
