name: 'Prepare Claude Run'
description: 'Checks if the workflow should run and gets PR info.'

inputs:
  run_type:
    description: "The type of run, e.g., 'review' or 'task'."
    required: false
    default: 'task'
  github_event_before:
    description: 'The SHA of the commit before the push (from synchronize event)'
    required: false
  github_event_after:
    description: 'The SHA of the commit after the push (from synchronize event)'
    required: false

outputs:
  head_sha:
    description: 'The SHA of the PR head commit.'
    value: ${{ steps.prepare.outputs.head_sha }}
  should_run:
    description: 'True if the workflow should proceed.'
    value: ${{ steps.prepare.outputs.should_run }}

runs:
  using: "composite"
  steps:
    - name: Check for force push
      id: force_push_check
      if: inputs.run_type == 'review' && github.event_name == 'pull_request' && github.event.action == 'synchronize'
      shell: bash
      run: |
        if [ -z "${{ inputs.github_event_before }}" ] || [ -z "${{ inputs.github_event_after }}" ]; then
          echo "is_force_push=false" >> $GITHUB_OUTPUT
        elif git merge-base --is-ancestor "${{ inputs.github_event_before }}" "${{ inputs.github_event_after }}" >/dev/null 2>&1; then
          echo "is_force_push=false" >> $GITHUB_OUTPUT
        else
          echo "is_force_push=true" >> $GITHUB_OUTPUT
        fi

    - name: Decide execution and get PR info
      id: prepare
      uses: actions/github-script@v7
      with:
        script: |
          const runType = '${{ inputs.run_type }}';
          const isForcePush = '${{ steps.force_push_check.outputs.is_force_push || 'false' }}' === 'true';

          let shouldRun = true;
          let headSha = '';
          let prNumber;

          // 1. Determine PR Number from context
          if (context.eventName === 'pull_request') {
              prNumber = context.payload.pull_request.number;
          } else if (context.eventName === 'issue_comment') {
              prNumber = context.payload.issue.pull_request ? context.payload.issue.number : undefined;
          } else if (context.eventName === 'pull_request_review_comment') {
              prNumber = context.payload.pull_request.number;
          }

          // 2. Authorization & Pre-checks
          if (!prNumber) {
              core.info('Not a pull request context. Skipping.');
              shouldRun = false;
          } else if (context.eventName.includes('comment')) {
              const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  username: context.actor,
              });
              const allowed = ['admin', 'maintain', 'write'];
              if (!allowed.includes(permission.permission)) {
                  core.info(`User '${context.actor}' with permission '${permission.permission}' is not authorized. Skipping.`);
                  shouldRun = false;
              }
          }

          if (shouldRun && context.eventName === 'pull_request' && context.payload.pull_request.head.repo.full_name !== `${context.repo.owner}/${context.repo.repo}`) {
              core.info('Pull request is from a fork. Skipping.');
              shouldRun = false;
          }

          // 3. Additional review-specific checks
          if (shouldRun && runType === 'review') {
              if (isForcePush) {
                  core.info('Force push detected. Skipping review.');
                  shouldRun = false;
              }
              const prTitle = (context.payload.pull_request?.title || '').toLowerCase();
              const skipPrefixes = ['docs:', 'style:', 'chore:', 'wip:'];
              if (shouldRun && skipPrefixes.some(p => prTitle.startsWith(p))) {
                  core.info(`Skipping review due to PR title prefix: ${prTitle}`);
                  shouldRun = false;
              }
          }

          // 4. Get Head SHA
          if (shouldRun) {
              if (context.eventName === 'pull_request') {
                  headSha = context.payload.pull_request.head.sha;
              } else { // Comments
                  try {
                      const { data: pr } = await github.rest.pulls.get({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: prNumber,
                      });
                      headSha = pr.head.sha;
                  } catch (error) {
                      core.error(`Failed to get PR info: ${error.message}`);
                      shouldRun = false;
                  }
              }
          }

          core.setOutput('should_run', shouldRun);
          core.setOutput('head_sha', headSha);